import {
  servicesWh,
  getPost,
  /*-PERFILES----------*/
  getPerfil,
  getPerfiles,
  getPerfilEdicion,
  getFichaCompleta,
  /*-USUARIOS----------*/
  registroUsuario,
  /*-PACIENTES---------*/
  serviciosPaciente,
  /*-AFILIADO----------*/
  serviciosAfiliados,
  /*-CONSULTAS--------*/
  getConsultasSinTokenCancel,
  serviciosConsultas,
  getConsultas,
  /*-ALERGIAS----------*/
  getAlergiasPaciente,
  getGrupoAlergias,
  getAlergias,
  /*-ENFERMEDADES---*/
  getEnfermedadPaciente,
  getEnfermedad,
  /*-LABORATORIO-----*/
  getLaboratorios,
  /*-IMAGENOLOGIA---*/
  getImagenologias,
  /*-TRATAMIENTOS----*/
  getMedicamentos,
  getTratamientosPacientes,
  getTipoDiagnosticosPacientes,
  /*-DISCAPACIDAD----*/
  getDicapacidadPaciente,
  /*-URL-----------------*/
  URLPERFIL,
  /*-MIS-MEDICAMENTOS-*/
  getMisMedicamentos,
  getDetailMedicamento,
} from "./servicios";
export {
  servicesWh,
  getPost,
  /*-PERFILES----------*/
  getPerfil,
  getPerfiles,
  getPerfilEdicion,
  getFichaCompleta,
  /*-USUARIOS----------*/
  registroUsuario,
  /*-PACIENTES---------*/
  serviciosPaciente,
  /*-AFILIADO----------*/
  serviciosAfiliados,
  /*-CONSULTAS--------*/
  getConsultasSinTokenCancel,
  serviciosConsultas,
  getConsultas,
  /*-ALERGIAS----------*/
  getAlergiasPaciente,
  getGrupoAlergias,
  getAlergias,
  /*-ENFERMEDADES---*/
  getEnfermedadPaciente,
  getEnfermedad,
  /*-LABORATORIO-----*/
  getLaboratorios,
  /*-IMAGENOLOGIA---*/
  getImagenologias,
  /*-TRATAMIENTOS----*/
  getMedicamentos,
  getTratamientosPacientes,
  getTipoDiagnosticosPacientes,
  /*-DISCAPACIDAD----*/
  getDicapacidadPaciente,
  /*-URL-----------------*/
  URLPERFIL,
  /*-MIS-MEDICAMENTOS-*/
  getMisMedicamentos,
  getDetailMedicamento,
};
