import {
  servicesWh,
  getPost,
  /*-PERFILES----------*/
  getPerfil,
  getPerfiles,
  getPerfilEdicion,
  /*-USUARIOS----------*/
  registroUsuario,
  /*-PACIENTES---------*/
  serviciosPaciente,
  /*-AFILIADO----------*/
  serviciosAfiliados,
  /*-CONSULTAS--------*/
  serviciosConsultas,
  getConsulta,
  /*-ALERGIAS----------*/
  getAlergiasPaciente,
  getGrupoAlergias,
  getAlergias,
  /*-ENFERMEDADES---*/
  getEnfermedadPaciente,
  getEnfermedad,
  /*-LABORATORIO-----*/
  getLaboratorio,
  /*-IMAGENOLOGIA---*/
  getImagenologia,
} from "./servicios";
export {
  servicesWh,
  getPost,
  /*-PERFILES----------*/
  getPerfil,
  getPerfiles,
  getPerfilEdicion,
  /*-USUARIOS----------*/
  registroUsuario,
  /*-PACIENTES---------*/
  serviciosPaciente,
  /*-AFILIADO----------*/
  serviciosAfiliados,
  /*-CONSULTAS--------*/
  serviciosConsultas,
  getConsulta,
  /*-ALERGIAS----------*/
  getAlergiasPaciente,
  getGrupoAlergias,
  getAlergias,
  /*-ENFERMEDADES---*/
  getEnfermedadPaciente,
  getEnfermedad,
  /*-LABORATORIO-----*/
  getLaboratorio,
  /*-IMAGENOLOGIA---*/
  getImagenologia,
};
